### ISSUE TITLE
Not clear what is and is not executed

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/python-scope-readme#1]
<img width="333" alt="screen shot 2018-04-01 at 2 42 38 pm" src="https://user-images.githubusercontent.com/13033515/38176343-f75e0408-35ba-11e8-8a7f-7467df8a806f.png">

I ran it and got 'what' which is great, but I don't think it really illustrates what was and was not executed. I think using `print()` here would help show this better.

@JeffKatzy

**Comment by tkoar** [comment]
added in print to more concretely show that the first string is read and the print is executed but the second print does not.
